cmake_minimum_required(VERSION 3.18)
project(pds_hdf5_unpack LANGUAGES C CXX)
find_package(HDF5 REQUIRED COMPONENTS C)
include(FetchContent)
FetchContent_Declare(daqdataformats GIT_REPOSITORY https://github.com/DUNE-DAQ/daqdataformats.git GIT_TAG dd12cf14f987fcc51aef003dbd38e51f8e80fd04 SOURCE_SUBDIR include)
FetchContent_Declare(detdataformats GIT_REPOSITORY https://github.com/DUNE-DAQ/detdataformats.git GIT_TAG 103123a4c915867a78bc7e67e576271393262da8 SOURCE_SUBDIR include)
FetchContent_Declare(fddetdataformats GIT_REPOSITORY https://github.com/DUNE-DAQ/fddetdataformats.git GIT_TAG 75451f42c049bf51132493075d61a1c884592425 SOURCE_SUBDIR include)
FetchContent_MakeAvailable(daqdataformats detdataformats fddetdataformats)
add_executable(pds-hdf5-unpack main.cpp)
target_compile_features(pds-hdf5-unpack PRIVATE cxx_std_20)
target_compile_definitions(pds-hdf5-unpack PRIVATE H5_USE_110_API)
target_include_directories(pds-hdf5-unpack PRIVATE ${HDF5_INCLUDE_DIRS} ${daqdataformats_SOURCE_DIR}/include ${detdataformats_SOURCE_DIR}/include ${fddetdataformats_SOURCE_DIR}/include)
target_link_libraries(pds-hdf5-unpack PRIVATE ${HDF5_LIBRARIES})
target_compile_options(pds-hdf5-unpack PRIVATE -Wall -Wextra -Wpedantic)
